language: c

#install:
# - sudo apt-get -y install gcc-arm-linux-gnueabihf 

matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: arm-linux-gnueabihf-gcc
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf

    - os: linux
      compiler: mingw32-gcc
      addons:
        apt:
          packages:
            - mingw32
            - mingw32-binutils
            - mingw32-runtime

script: make
