language: c

matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: arm-linux-gnueabihf-gcc
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf
            - linux-libc-dev-armhf-cross

    - os: linux
      dist: trusty
      compiler: aarch64-linux-gnu-gcc
      addons:
        apt:
          packages:
            - gcc-aarch64-linux-gnu
            - linux-libc-dev-arm64-cross

    - os: linux
      compiler: i586-mingw32msvc-gcc
      addons:
        apt:
          packages:
            - mingw32
            - mingw32-binutils
            - mingw32-runtime

    - os: linux
      compiler: x86_64-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - gcc-mingw-w64

script:
  - make
  - x86_64-w64-mingw32-objdump -d x86-sse2.o
