language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      script:
        - make

    - os: linux
      compiler: arm-linux-gnueabihf-gcc
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - qemu-user
      script:
        - CFLAGS="-O2 -mfpu=neon -g -static -DMAXREPEATS=2 -DLATBENCH_COUNT=10000" make
        - qemu-arm ./tinymembench

    - os: linux
      dist: trusty
      compiler: aarch64-linux-gnu-gcc
      addons:
        apt:
          packages:
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross
            - qemu-user
      script:
        - CFLAGS="-O2 -g -static -DMAXREPEATS=2 -DLATBENCH_COUNT=10000" make
        - qemu-aarch64 ./tinymembench

    - os: linux
      compiler: i586-mingw32msvc-gcc
      addons:
        apt:
          packages:
            - mingw32
            - mingw32-binutils
            - mingw32-runtime
      script:
        - CFLAGS="-O2 -g -DMAXREPEATS=2 -DLATBENCH_COUNT=10000" make
        - i586-mingw32msvc-objdump -d ./tinymembench
        # Fails because of https://sourceware.org/bugzilla/show_bug.cgi?id=12687
        # - wine ./tinymembench

    - os: linux
      compiler: x86_64-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - gcc-mingw-w64
            - wine
      script:
        - CFLAGS="-O2 -g -DMAXREPEATS=2 -DLATBENCH_COUNT=10000" make
        - wine ./tinymembench

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GB9wLaH72mzLlMxy7bVVkIAu/whCc7YIP53lM80U57L0WBQ3BTcrklTYdjUVsHBpDBVhKzZwkLeRs1lySHnFKVg5XuQYrC3bdY/0XdgdSfXggdpw7prwrQz6MVGIK3ilMHyOhJ5IZkLDyLUQy4H+xCkiDhxFG76O//Mx904SszCWKggc9QU6ipdjgfsvwkxG0Sr3vsb1YjpVczNtZx2VoWXRLmPjtAUnZQOHZWuwz7+DDZ5lkAN3HMGVjFiv00MkwiXG51jjnd3nMqjEjp98H6ArZGy3t8++As7OVDORTgxP3yE5ApQiZO0Pa4itapbIdfi0QVsRl+EN6SCFO+D3QgenZtSGyyv8+V43qI886ngwxf0yQUGC/0JYDStzLL4gVYKDeE7II/XbqiyvCq907HHbvBIHpCMgWygbVMwm+ig2PE2XV6rm+TDfFOZ0RDX+Se7u/zhsaQTcRyQVmZ635D1mFKFUPx/bxTsj7I9fDgob26YxQywDRLQKsyNKDKMFsRqP6D4if4+BPGxjao2x8ZvxWnvGM9atjug2CBet3pj8HzUKDKoSnMoFnQuuOV38vPAPEAEDOhgy+AkykO7OGrUR8dkSDE2MehoeE0MOKAlNwpxYIYaF1QjOlV/FoltpVxQ7Qg0/7L+Lzx4qoG08hS4Iu+379YaIOcpT2+1uHxg="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ssvb/tinymembench"
      description: "Build submitted via Travis CI"
    notification_email: siarhei.siamashka@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
