language: c

#install:
# - sudo apt-get -y install gcc-arm-linux-gnueabihf 

matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: arm-linux-gnueabihf-gcc
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf

    - os: linux
      compiler: i686-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - mingw32
            - mingw32-binutils
            - mingw32-runtime

    - os: linux
      compiler: x86_64-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - gcc-mingw-w64

script: make
